FROM nvcr.io/nvidia/tensorrt:22.04-py3
RUN pip install torch torchvision torchaudio
RUN apt-get install -y build-essential devscripts debhelper fakeroot \
RUN apt-get  apt-get install -y libnuma-dev vim openssh-server zsh fzf